# The build part might fail, test later

services:
  balti:
    image: ghcr.io/mradigen/balti
    pull_policy: build
    labels:
      - traefik.enable=true
      - traefik.http.routers.balti.rule=Host(`b.phy0.in`)
