services:
  borgmatic:
    image: ghcr.io/borgmatic-collective/borgmatic
    container_name: borgmatic
    volumes:
	    - ${VOLUME_SOURCE}:/mnt/source:ro            # backup source
	  #- ${VOLUME_TARGET}:/mnt/borg-repository      # backup target
      - ${DATA_PATH}:/etc/borgmatic.d/  # borgmatic config file(s) + crontab.txt
	  #- ${VOLUME_BORG_CONFIG}:/root/.config/borg   # config and keyfiles
      - ${VOLUME_SSH}:/root/.ssh                   # ssh key for remote repositories
      - ${VOLUME_BORG_CACHE}:/root/.cache/borg     # checksums used for deduplication
    environment:
      - BACKUP_CRON
      - TZ
      - BORG_PASSPHRASE
