- name: Setup Kubernetes1
  hosts: kubernetes1
  become: true
  vars:
    username: adigen
    sshd_port: "{{ lookup('env', 'SSH_PORT') | mandatory }}"
    network_interface: ens18
    tailscale_preauthkey: "{{ lookup('env', 'TAILSCALE_PREAUTHKEY') | mandatory }}"

    k3s_url: "{{ lookup('env', 'K3S_URL') }}"
    k3s_token: "{{ lookup('env', 'K3S_TOKEN') }}"

  tasks:
    - import_tasks: tasks/firewalld.yml
    - import_tasks: tasks/utils.yml
    - import_tasks: tasks/user.yml
    - import_tasks: tasks/docker.yml
    - import_tasks: tasks/tailscale.yml
    - import_tasks: tasks/k3s.yml
