services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: pass
    restart: unless-stopped
    environment:
      DOMAIN: ${DOMAIN:?}
    volumes:
      - ${DATA_PATH:?}:/data/
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.pass.middlewares=tailscale'
