global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node_exporters'
    static_configs:
      - targets:
          - 'vyria:9220'

  - job_name: 'cadvisor'
    static_configs:
      - targets:
          - 'vyria:9221'
