services:
  headscale:
    image: headscale/headscale:0.24.2
    restart: unless-stopped
    container_name: headscale
    expose:
      - 8080
    volumes:
      - ${DATA_PATH}:/etc/headscale
    command: serve
    labels:
      - 'traefik.enable=true'

  headscale-admin:
    image: goodieshq/headscale-admin:latest
    container_name: headscale-admin
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
