services:
  headscale:
    image: headscale/headscale:0.26.0
    restart: unless-stopped
    container_name: headscale
    expose:
      - 8080
    volumes:
      - ${DATA_PATH:?}/config:/etc/headscale
      - ${DATA_PATH:?}/data:/var/lib/headscale
    command: serve
    labels:
      - traefik.enable=true

  headscale-admin:
    image: goodieshq/headscale-admin:latest
    container_name: headscale-admin
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.headscale-admin.rule=Host(`headscale.phy0.in`) && PathPrefix(`/admin`)
      - traefik.http.routers.headscale-admin.middlewares=tailscale
