services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped
    volumes:
      - ${DATA_PATH:?}:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: host # For using host tailscale
    environment:
      HOMEPAGE_ALLOWED_HOSTS: "home.phy0.in,vyria:3000"
      # HOMEPAGE_ALLOWED_IPS: ${TAILSCALE_ALLOWED_IPS}
    
  proxy: # need this cause homepage doesn't support basic auth on caldav
    image: nginx:alpine
    container_name: home # this container is named home for traefik subdomain.
    volumes:
      - ${DATA_PATH:?}/nginx.conf:/etc/nginx/nginx.conf:ro
    ports: # this is exposed for homepage to fetch dav data
      - "3001:80"
    restart: unless-stopped
    network_mode: host # inorder to access homepage host 3000 port
    labels:
      - traefik.enable=true
