services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: home
    restart: unless-stopped
    volumes:
      - ${DATA_PATH:?}:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: host
    environment:
      HOMEPAGE_ALLOWED_HOSTS: home.phy0.in
    labels:
      - traefik.enable=true
      - traefik.http.services.home.loadbalancer.server.port=3000
    
  proxy: # need this cause homepage doesn't support basic auth on caldav
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"