- name: Install k3s agent (or join existing cluster)
  shell: |
    wget -qO- https://get.k3s.io | K3S_URL={{ k3s_url }} K3S_TOKEN={{ k3s_token }} sh -
  args:
    creates: /usr/local/bin/k3s

- name: Open port 6443/tcp for API server
  firewalld:
    port: 6443/tcp
    permanent: yes
    immediate: yes
    state: enabled

- name: Trust pod network source 10.42.0.0/16
  firewalld:
    source: 10.42.0.0/16
    zone: trusted
    permanent: yes
    state: enabled

- name: Trust service network source 10.43.0.0/16
  firewalld:
    source: 10.43.0.0/16
    zone: trusted
    permanent: yes
    state: enabled
