- name: Install utility packages
  apt:
    name:
      - mosh
      - openssh-server
      - btop
      - screen
      - sudo
      - ranger
      - neovim
    state: present
    update_cache: true

- name: Change SSHD port in sshd_config
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?Port '
    line: "Port {{ sshd_port | mandatory }}"
    backup: yes

- name: Open SSHD port in firewalld
  firewalld:
    port: "{{ sshd_port | mandatory }}/tcp"
    permanent: yes
    immediate: yes
    state: enabled

- name: Open mosh UDP port range in firewalld
  firewalld:
    port: 60000-61000/udp
    permanent: yes
    immediate: yes
    state: enabled
