services:
  tui_suite:
    image: ghcr.io/mradigen/tui_suite
    volumes:
      - docker_cache:/var/lib/docker
      - ssh_keys:/etc/ssh
      - ./.runtimefs:/home/tui_suite/.runtimefs
    privileged: true
    ports:
      - 22:22
    restart: unless-stopped

volumes:
  docker_cache:
  ssh_keys:
