- name: Fetch from Vault
  set_fact:
    # no need to mention secret= if its the first parameter
    env_vars: "{{ lookup('community.hashi_vault.vault_kv2_get', 'docker/{{ service_name }}').secret }}"

- name: "Ensure {{ docker_home_path }}/{{ service_name }}/ directory exists"
  file:
    path: "{{ docker_home_path }}/{{ service_name }}"
    state: directory

- name: "Copy the variables to {{ docker_home_path }}/{{ service_name }}/.env from Vault"
  copy:
    dest: "{{ docker_home_path }}/{{ service_name }}/.env"
    mode: "0640"
    content: |
      {% for key, val in env_vars.items() %}
      {{ key }}={{ val }}
      {% endfor %}
  register: vars_update

# UNTESTED:

- name: "Restart service if its variables have changed"
  when: update_all_services or vars_update.changed
  block:
    - name: "Take {{ service_name }} down"
      community.docker.docker_compose_v2:
        project_src: "{{ docker_home_path }}/{{ service_name }}"
        state: absent
    #
    # - name: "Put {{ service_name }} back up"
    #   community.docker.docker_compose_v2:
    #     project_src: "{{ docker_home_path }}/{{ service_name }}"
    #     state: present
